### ISSUE TITLE
请教rc6版本下用webpack怎么实现lazyload？

### ISSUE THREAD

**Issue by qk44077907** [WuKongW/Angular2_POC#5]

**Comment by WuKongW** [comment]
在Angular2 RC5以后，Lazy Loading跟打包工具（Webpack, gulp, angular-cli 等等）就没有很大的关系了，在新版本中你只需要把你要做Lazy Loading的模块放在module中，并在routing中用**loadChildren**去加载它，Angular2底层就会自动给你做懒加载。等项目上线的时候你需要做的是把loadChildren中的module按照你写的路径单独打成一个文件（因为Angualr2底层是通过systemJS去加载的），这样webpack才能去加载它~

比如这里的：https://github.com/WuKongW/Angular2_POC/blob/master/app/common/router/app.routing.ts

{ path: 'about', loadChildren: 'app/+about/about.module' }
最终你要打包出一个about.module.js在app/+about文件夹下面

我在这里也做了简单的介绍：
http://my.oschina.net/wukong1988/blog/741255

**Comment by qk44077907** [comment]
@WuKongW 我的项目没有用system.js来启动整个app，这是问题所在。正如你所说RC5及以前的版本使用system.js来实现懒加载的。

**Comment by WuKongW** [comment]
@qk44077907 我不清楚我对你的项目理解的对不对，Angular2只是在底层用SystemJS来做资源加载的，应该跟你的项目使用SystemJS还是Webpack没什么关系，我觉得你的问题应该是打包这里出问题了。就像我上面说的“最终你要打包出一个about.module.js在app/+about文件夹下面”，不管你是用webpack 还是其他的最终你都是要打成多个可做懒加载的文件而不是一个bundle文件。

{path: "about", loadChildren: () => require("es6-promise!../+about/about.module)("AboutModule") }

webpack打包的输出中
output: {
  path: path.resolve('build'),
  filename: '[name].js',       // 这里的 [name] 是重点
  publicPath: '/'
}

**Comment by qk44077907** [comment]
@WuKongW https://www.npmjs.com/package/angular2-load-children-loader  
这个是一个webpack2的module的loader,最后一段AOT与JIT的区别我不是很懂，不过既然有人单独写一个loader，直接写loadChildren: () => require("es6-promise!../+about/about.module)("AboutModule")应该不能满足所有场景吧

**Comment by qk44077907** [comment]
https://github.com/angular/angular-cli/pull/1632

我现在是在RC5版本下用这个别人写的loader来实现的懒加载，RC6里不知道还用不用引入别人写的loader
https://gist.github.com/brandonroberts/02cc07face25886fe142c4dbd8da1340

**Comment by WuKongW** [comment]
@qk44077907 AOT跟JIT是指你的代码在server端编译还是client端编译，上面这个loader就是把

{ path: 'about', loadChildren: 'app/+about/about.module' }

输出成：

{path: "about", loadChildren: () => require("es6-promise!../+about/about.module)("AboutModule") }

并不是说你网站启动的时候用别人写的loader去做懒加载，在RC 5之后懒加载是Angular2原生支持的，真正做懒加载的是Angular2自己的loadChildren命令，跟工具（webpack）没关系。。。别人写的这些loader只是为了辅助webpack打包，要知道你如果不用webpack的话你是根本不需要额外的loader之类的东西的，所以loadChildren肯定是可以满足所有场景的
